# FactoryBot factory for creating UserTask instances in tests.
#
# This factory creates a UserTask with default attributes including:
# - A user association (created via the :user factory)
# - A task association (created via the :task factory)
# - Random submission text generated by Faker
# - Current timestamp for submission date
# - A completed status of true
#
# Usage in tests:
#   create(:user_task)                          # Creates a saved UserTask with all defaults
#   build(:user_task)                           # Creates an unsaved UserTask instance
#   create(:user_task, completed: false)        # Creates with custom attributes
#
# CLI usage:
#   rails console
#   > FactoryBot.create(:user_task)
#   > FactoryBot.build(:user_task, submitted_at: 2.days.ago)
FactoryBot.define do
  factory :user_task do
    association :user
    association :task
    submission_text { Faker::Lorem.paragraph }
    submitted_at { Time.current }
    completed { true }
  end
end
